{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "b8f35e4e",
   "metadata": {},
   "source": [
    "**Wind Turbine Case Study Outline**\n",
    "\n",
    "I. Introduction\n",
    "\n",
    "A. Overview of wind turbine design\n",
    "\n",
    "1. Importance of wind energy in the renewable energy sector - Wind turbines use blades to collect the wind's kinetic energy. Wind flows over the blades creating lift which causes the blades to turn. The blades are connected to a drive shaft that turns an electric generator, which produces electricity (https://www.eia.gov/energyexplained/wind/electricity-generation-fromwind.php#:~:text=How%20wind%20turbines%20work,which%20produces%20(generates)%20electricity.). Wind electricity generation has grown significantly in the past 30 years. Advances in wind-energy technology have decreased the cost of wind electricity generation. Total annual U.S. electricity generation from wind energy increased from about 6 billion kilowatt-hours (kWh) in 2000 to about 434 billion kWh in 2022. In 2022, wind turbines were the source of about 10.3% of total U.S. utility-scale electricity generation.\n",
    "\n",
    "2. Basic components of wind turbine design – The three major components of a wind turbine are a rotor, nacelle, and tower (https://www.nyserda.ny.gov/-/media/Project/Nyserda/Files/Publications/Research/Biomass-Solar-Wind/NY-Wind-Energy-Guide-1.pdf). The rotor consists of a hub and three blades. The hub is the link between the blades and shaft. The blades obtain kinetic energy from the wind. This is converted to torque and transferred to the gearbox through the shaft. To maximize energy capture, the turbine rotates on its vertical axis to position the rotor in the direction of the wind using a yawning mechanism (https://www.nyserda.ny.gov/-/media/Project/Nyserda/Files/Publications/Research/Biomass-Solar-Wind/NY-Wind-Energy-Guide-1.pdf). The major components in the nacelle include the gearbox and generator. The rotor and gearbox are connected using a low-speed shaft. The gearbox and generator are connected using a high-speed shaft. The rotation of the blades converts a low-speed, high-torque to a high-speed, low-torque rotational force transferred to the generator using the gearbox (https://www.nyserda.ny.gov/-/media/Project/Nyserda/Files/Publications/Research/Biomass-Solar-Wind/NY-Wind-Energy-Guide-1.pdf). The tower is connected to the ground and the rotor and nacelle are connected to the top of the tower. The tower is typically 262-360 feet.\n",
    "\n",
    "B. Definition of uncertainty to wind turbine design\n",
    "\n",
    "1. Types of uncertainty – The types of uncertainty in wind turbine design include aleatoric and epistemic uncertainty (https://www.nrel.gov/wind/assets/pdfs/se17-2-uncertainty-in-wind-turbine-design-process.pdf). Aleatoric uncertainty if fixed and includes uncertainty in due to turbulence and material yield/ fatigue stress (https://www.nrel.gov/wind/assets/pdfs/se17-2-uncertainty-in-wind-turbine-design-process.pdf). This also includes uncertainty in the environment and loads the structure experiences. These uncertainties require probabilistic mathematical methods to understand the uncertainty involved (https://wes.copernicus.org/articles/5/171/2020/.). Epistemic uncertainty is reducible and includes uncertainty in site condition parameters and aerodynamic models. \n",
    "\n",
    "II. Sources of Uncertainty in Wind Turbine Design\n",
    "\n",
    "A. Wind Resource Assessment\n",
    "\n",
    "1. Variability in wind speeds and directions – Wind speed increases as height increases. Power production might be suboptimal if win speed changes vertically across the area of the rotor swept (https://www.nrel.gov/docs/fy20osti/78107.pdf). This is known as wind speed shear. Directional shear means that the wind can be misaligned with the rotor if the wind direction changes across the area of the rotor swept (https://www.nrel.gov/docs/fy20osti/78107.pdf). Directional sheer impacts winds speed in the horizontal direction which can impact the energy through the rotor which can impact the turbine’s ability to extract energy.\n",
    "\n",
    "B. Structural and Material Properties\n",
    "\n",
    "1. Variability in material strength and fatigue life – Wind turbines utilize many different materials. Steel is often used in the tower and nacelle as it has a high tensile strength and durability (https://energy.sandia.gov/wp-content/gallery/uploads/SAND-2006-7810p.pdf). Fiberglass and carbon fiber composites are often used for blades as they have a high strength-to-weight ratio (https://energy.sandia.gov/wp-content/gallery/uploads/SAND-2006-7810p.pdf). Aluminum is often used for some components because of its lightweight properties and corrosion resistance. The materials go through different manufacturing processes which leads to differences in material properties. Environmental exposure such as UV radiation, moisture, temperature fluctuations and salt sprayed in offshore turbines affect the material strength over time (https://energy.sandia.gov/wp-content/gallery/uploads/SAND-2006-7810p.pdf). Additionally, fatigue cycles are impacted by load cycles, geometry, and operational conditions. Stress concentration and magnitude of load cycles greatly impact the fatigue cycles of the materials in wind turbines.\n",
    "\n",
    "C. Load Estimations\n",
    "\n",
    "1. Aerodynamic and operational loads – Aerodynamic loads are caused by wind shear and fluctuation forces from turbulence (https://www.nrel.gov/docs/fy99osti/25787.pdf). Varying wind speeds and rotational speeds affect the aerodynamic load applied. Gravitation force on the blade can cause variation in size, mass density, and shape of the blades. These loads have a big impact on wind turbines.\n",
    "\n",
    "D. Environmental Conditions\n",
    "\n",
    "1. Temperature fluctuations – Wind turbines must be able to withstand temperature variations across all seasons. International design standards mandate that turbines must be operational at a minimum of -4O F (https://climate.mit.edu/ask-mit/it-true-wind-turbines-dont-work-winter). Turbines must also withstand the hotter temperatures experienced in the summer.\n",
    "\tHumidity and corrosive environments – Areas of high humidity can cause corrosion on wind turbines (https://fisair.com/applications/aerogenerators/). Understanding the impact of humidity is important to the operating life of the turbines.  Additionally, corrosion increases exponentially in environments near bodies of water. In marine environments, humidity increases which impacts material life. Metal starts to deteriorate rapidly at environment with 60% relative humidity (https://fisair.com/applications/aerogenerators/). \n",
    "\n",
    "III. Methods to Address Uncertainty\n",
    "\n",
    "A. Probabilistic Design approaches\n",
    "\n",
    "1. Monte Carlo simulations – Monte Carlo simulations are often used to address uncertainty in wind turbine design. Monte Carlo is the most simple sampling technique. Monte Carlo methods use random sampling to create a probability distribution (https://www.researchgate.net/profile/Benjamin-Sanderse/publication/319209260_Uncertainty_quantification_for_wind_energy_applications_-_Literature_review/links/599c20ef45851574f4ac8b9e/Uncertainty-quantification-for-wind-energy-applications-Literature-review.pdf). Monte Carlo simulations are often used to obtain wind turbine output power at each hour. Using Monte Carlo methods, the input variables are modelled with associated uncertainty and address the cumulative impact on the variables outputted (https://www.researchgate.net/profile/Benjamin-Sanderse/publication/319209260_Uncertainty_quantification_for_wind_energy_applications_-_Literature_review/links/599c20ef45851574f4ac8b9e/Uncertainty-quantification-for-wind-energy-applications-Literature-review.pdf). Monte Carlo simulations are simple and easier to develop but often other methods produce more accurate results.\n",
    "\n",
    "2. Reliability-based design optimization (RBDO) – Design using RBDO focuses on specific limits of probability on structural performance (https://wes.copernicus.org/articles/5/171/2020/). RBDO is applied extensively in offshore wind turbine design, where environmental conditions are severe, and reliability is important. RBDO uses limit constraints and probabilities to determine probability of failure (https://wes.copernicus.org/articles/5/171/2020/). RBDO can be modeled using the following equations:\n",
    "                                              Pf = Prob(Q – R > 0)                                         (1)\n",
    "                                                  Pf = Prob(g > 0)                                             (2)\n",
    "                                            Pf = ∫_(g(x,Ɵ)>0)^∞▒〖h_Ɵ (Ɵ^' )dƟ'〗                                      (3)\n",
    "where Pf is probability of failure, Q is load effect, R is resistance, g is limit state function, hƟ is joint probability distribution and Ɵ is stochastic variables. Reliability-based design optimization methods are robust and simple for calculating probability of failure.\n",
    "\n",
    "3. Weibull distribution – Weibull distribution is often used to accurately estimate energy production and wind speed. Weibull distribution is commonly used as it predicts wind conditions and inverse of wind direction (https://www.researchgate.net/profile/Benjamin-Sanderse/publication/319209260_Uncertainty_quantification_for_wind_energy_applications_-_Literature_review/links/599c20ef45851574f4ac8b9e/Uncertainty-quantification-for-wind-energy-applications-Literature-review.pdf). Weibull distribution uses wind speed and shape parameters to create a probability function. An example of a Weibull distribution equation is modeled below:\n",
    "\n",
    "\t                                 (4)\n",
    "Modelling Weibull distribution can help accurately estimate uncertainty. An example of a Weibull distribution for wind speed is graphed below:\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "Figure 1: Example of a Weibull distribution for wind speed.\n",
    "Weibull distribution is effective for calculating probability of failure.\n",
    "\n",
    "4. Blade-Element-Momentum theory (BEM) – BEM is used in designing blades for a wind turbine and analyzing loading scenarios. BEM provides some acceptable results but also can have an error of up to 20% (https://www.researchgate.net/profile/Benjamin-Sanderse/publication/319209260_Uncertainty_quantification_for_wind_energy_applications_-_Literature_review/links/599c20ef45851574f4ac8b9e/Uncertainty-quantification-for-wind-energy-applications-Literature-review.pdf). Accurate aircoil lift and drag coefficients are needed for accurate results for BEM. BEM can be utilized using computational fluid dynamic models. These can be modeled is software such as Ansys and OpenFOAM (https://www.researchgate.net/profile/Benjamin-Sanderse/publication/319209260_Uncertainty_quantification_for_wind_energy_applications_-_Literature_review/links/599c20ef45851574f4ac8b9e/Uncertainty-quantification-for-wind-energy-applications-Literature-review.pdf). In these models, various loading conditions and materials can be applied to obtain results.\n",
    "\n",
    "IV. Conclusion\n",
    "\n",
    "A. Summary of key points – types of uncertainty, sources of uncertainty, methods to address uncertainty including Monte Carlo, BDMO, Weibull distribution, and BEM.\n",
    "\n",
    "B. Future outlook for wind turbine design – Integration of AI and machine learning to wind turbine design and impact of hybrid systems."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "69027827",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "jupytext": {
   "formats": "ipynb,md:myst"
  },
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
